export const ABSURD_DISHES = [
  'Spaghetti z wężami morskimi',
  'Klopsiki w chmurze czekoladowej',
  'Grzanki z dżemem z kaktusów',
  'Zupa szczęścia',
  'Flaczki z kosmicznego mięsa',
  'Placek z nutellą i brokułami',
  'Lody z ogórków kiszonych',
  'Pierogi z nadzieniem z kosmicznych pierwiastków',
  'Sałatka z meteorami z serem feta',
  'Zapiekanka z kolorowymi pyłkami kwiatowymi',
  'Ryż z gwiazdkami kosmicznymi',
  'Placki z księżycowej mąki',
  'Gulasz z elfiego mięsa',
  'Zupa z żabich baloników',
  'Klopsiki z duchów',
  'Lody smakujące jak tęcza',
  'Kawałki słońca w polewie karmelowej',
  'Lasagne z wampirzym serem',
  'Sałatka z magicznymi składnikami',
  'Placuszki z króliczymi skokami',
  'Ciasto z marsjańskim kremem',
  'Zupa z nutellą i pikselami',
  'Bułeczki z duszonymi dźwiękami',
  'Zestawienie czekoladowych chmur na pizzy',
  'Smażony dyskietowy kurczak',
  'Syfoniada z dźwiękami oceanu',
  'Wafelki w kształcie spirali czasoprzestrzennej',
  'Mini bułeczki z aromatycznymi cząstkami galaktyk',
  'Kiełbaski z soczewicą z czarnej dziury',
  'Deser z trzema wymiarami czekolady',
  'Kawa z dodatkiem światłowodów smakowych',
  'Klopsiki z kometarnym pyłem',
  'Eksplozja truskawkowa w kosmicznej kuli lodowej',
  'Spaghetti w tajemniczym soku z ogórków',
  'Sałatka z marakują i mgiełką cytrynową',
  'Tagliatelle z trującymi grzybami',
  'Pieczony łosoś w pikantnym sosie z agrestu',
  'Klasyczne klopsiki w zalewie tryskającej fantazji',
  'Zupa krem z fusów z zielonej herbaty',
  'Risotto z ziołowym szaleństwem',
  'Indyk w sosie z połamanej czekolady',
  'Sałatka z dziką miętą i zielonymi jabłkami',
  'Tatar z łososia z posypką kwasów',
  'Zupa krem z zapomnianej marchwi',
  'Medaliony z szalonych pomidorów w truflowej otulinie',
  'Spaghetti z sosem z perlistych oliwek',
  'Kaczka w sosie ze śnieżnej mięty',
  'Tagliatelle z sosem ze słońca zachodzącego nad morzem',
  'Klasyczne klopsiki w delicji różowych płatków',
  'Zupa krem z podwójnym espresso',
  'Risotto z grzybów rosnących w magicznym lesie',
  'Indyk w sosie z owoców baobabu',
  'Sałatka z pomarańczowym mlekiem jednorożca',
  'Tatar z łososia w zaczarowanej miodowej polewie',
  'Polędwiczki w kapeluszu szaleńca',
  'Spaghetti w tajemniczym soku z ogórków',
  'Sałatka z marakują i mgiełką cytrynową',
  'Tagliatelle z trującymi grzybami',
  'Pieczony łosoś w pikantnym sosie z agrestu',
  'Zupa krem z fusów z zielonej herbaty',
  'Indyk w sosie z połamanej czekolady',
  'Tatar z łososia podgrzewany promieniami słońca',
  'Penne z sosem z szeptem bazylii',
  'Tarta z serem chóru aniołów',
  'Kanapki z miodem z pszczół wędrownych',
  'Omlet z kropelkami porannej rosy',
  'Zupa z kwiatów wiśni i odrobiny nostalgii',
  'Ciasto marchewkowe z nutą tajemniczego przyprawnika',
  'Chipsy z liści magicznej paproci',
  'Sałatka z ogórków i sny szczęśliwego ogrodnika',
  'Smażone pierożki z nadzieniem z leśnej ściółki',
  'Deser z rozgrzanego masła polanych płatkami róż',
  'Gulasz wędrowców górskich z grzybami wysokich szczytów',
  'Zupa pomidorowa z odrobiną letniej burzy',
  'Ciastka przywołujące zapach jesiennego lasu',
  'Herbata z aromatem snów o poranku',
  'Tosty z masłem wiatrów wrześniowych',
  'Kluski w sosie babcinych opowieści',
  'Pieczone jabłka z cynamonem porannej mgły',
  'Ciastka z niewidzialnym dżemem',
  'Lasagne z cieni burzy',
  'Koktajl z odprysków gwiezdnych skał',
  'Placki z promieniem zorzy polarnej',
  'Bagietka z esencją porannej rosy',
  'Suflet z westchnień wiatru pustyni',
  'Krem karmelowy z kroplą mgły oceanicznej',
  'Mus z tańczącej drobiny srebra',
  'Chleb z oddechem smoka',
  'Herbatka z liści snów o przygodach',
];
